Parameters:
  Name:
    Type: String
  VPCCIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/16
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/24
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.1.0/24
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.2.0/24
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.3.0/24
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.4.0/24
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.5.0/24
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String

Resources:
  AlanVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      Tags:
      - Key: Name
        Value: !Ref Name

  AlanInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Ref Name

  AlanAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AlanVPC
      InternetGatewayId: !Ref AlanInternetGateway

  AlanPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AlanVPC
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: !Sub ${Name}-PublicSubnet1

  AlanPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AlanVPC
      CidrBlock: !Ref PublicSubnet2CIDR
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: !Sub ${Name}-PublicSubnet2

  AlanPublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AlanVPC
      CidrBlock: !Ref PublicSubnet3CIDR
      AvailabilityZone: "us-west-2c"
      Tags:
      - Key: Name
        Value: !Sub ${Name}-PublicSubnet3

  AlanPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AlanVPC
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: !Sub ${Name}-PrivateSubnet1

  AlanPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AlanVPC
      CidrBlock: !Ref PrivateSubnet2CIDR
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: !Sub ${Name}-PrivateSubnet2

  AlanPrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AlanVPC
      CidrBlock: !Ref PrivateSubnet3CIDR
      AvailabilityZone: "us-west-2c"
      Tags:
      - Key: Name
        Value: !Sub ${Name}-PrivateSubnet3


  AlanPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AlanVPC
      Tags:
        - Key: Name
          Value: !Sub ${Name}-PublicRouteTable

  AlanPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AlanVPC
      Tags:
        - Key: Name
          Value: !Sub ${Name}-PrivateRouteTable

  AlanPublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AlanPublicSubnet1
      RouteTableId: !Ref AlanPublicRouteTable

  AlanPublicSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AlanPublicSubnet2
      RouteTableId: !Ref AlanPublicRouteTable

  AlanPublicSubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AlanPublicSubnet3
      RouteTableId: !Ref AlanPublicRouteTable

  AlanPrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AlanPrivateSubnet1
      RouteTableId: !Ref AlanPrivateRouteTable

  AlanPrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AlanPrivateSubnet2
      RouteTableId: !Ref AlanPrivateRouteTable

  AlanPrivateSubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AlanPrivateSubnet3
      RouteTableId: !Ref AlanPrivateRouteTable

  AlanRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AlanPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AlanInternetGateway